### ISSUE TITLE
Broken latte syntax highlighting during editing string in tag {var $test = 'abc'}

### ISSUE THREAD

**Issue by mildabre** [mesour-intellij-plugins/latte-pro-issues#107]
**Describe the bug**

Specific combination of latte tag {var} with html tag with attribute defined by latte produces broken syntax highlighting of the plugin.

The bug appears during writing tag {var} - more precisely during writing/editing the string 'abc' in {var $test = 'abc'}

I have tested long time exact syntax which makes/makes not this troubles and send you a list of code samples as documentation for repair the plugin.

**Environment:**

Latte Pro 1.0.11
PHPstorm 2023.1.1

**To Reproduce**

a) copy individually pair of lines of latte code to latte file and try to edit the string 'abc' in tag  {var $test = 'abc'} - the syntax gets broken

b) after the syntax gets broken close and reopen the latte file and see that syntax is OK, it brokes only during editing

**Code  - samples of BROKEN syntax**

```
{var $test = 'abc'}
<p class="{$var ?? ''}"></p>


{var $test = 'abc'}
<p class="{$object->method($var)}"></p>


{var $test = 'abc'}
<p class="{$var.'string'}"></p>


{var $test = 'abc'}
<p class="{$object->property.'string'}"></p>


{var $test = 'abc'}
<p class="{$object->method().'string'}"></p>


{var $test = 'abc'}
{*	<p class="{$var ?? ''}"></p>*}


{var $test = $var2.'abc'}
<p class="{$var ?? ''}"></p>
```

**Code  - samples of NOT BROKEN syntax**

```
{var $test = 'abc'}
{$var ?? ''}


{var $test = 'abc'}
<p>{$var ?? ''}</p>


{var $test = 'abc'}
<p n:href="$var ?? ''"></p>


{var $test = 'abc'}
<p class="{$var}"></p>


{var $test = 'abc'}
<p class="{$object->property}"></p>


{var $test = 'abc'}
<p class="{$object->method()}"></p>


<p class="{$var.'abc'}"></p>
{var $test = 'string'}

{var $test = $var1.$var2}
<p class="{$var ?? ''}"></p>
```

**Conclusion**

 a) problematic is using string in tag {var} in combination with some {php_expression} inside the html attribute
 b) the same {php_expression} out of html attribute makes no problems
 c) syntax gets broken when editing string in latte {var}, when not editing syntax is OK
 d) php expressions making troubles are many types - with string, with operator ??, ?, method with argument, etc...
 e) troubles makes also expressions commented by latte comment !!

**Exception**

When the syntax gets broken plugin indicates this exception:

Text mismatch in Outer HTML/XML in Latte (com.mesour.intellij.latte.psi.at)

com.intellij.diagnostic.PluginException: Text mismatch [Plugin: com.mesour.intellij.latte]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.assertTextLengthIntact(LazyParseableElement.java:208)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$2(LazyParseableElement.java:186)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:184)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:236)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:126)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:33)
	at com.intellij.psi.AbstractFileViewProvider.findElementAt(AbstractFileViewProvider.java:242)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.findElementAt(MultiplePsiFilesPerDocumentFileViewProvider.java:162)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.findElementAt(MultiplePsiFilesPerDocumentFileViewProvider.java:174)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:531)
	at com.intellij.psi.util.PsiUtilCore.getElementAtOffset(PsiUtilCore.java:407)
	at com.intellij.psi.util.PsiUtilBase.getLanguageInEditor(PsiUtilBase.java:56)
	at com.intellij.psi.util.PsiUtilBase.getPsiFileInEditor(PsiUtilBase.java:92)
	at com.intellij.psi.util.PsiUtilBase.getPsiFileInEditor(PsiUtilBase.java:76)
	at com.intellij.codeInsight.highlighting.BackgroundHighlightingUtil.lambda$lookForInjectedFileInOtherThread$0(BackgroundHighlightingUtil.java:47)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:746)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:778)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:573)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:107)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:444)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mildabre** [comment]
Hi,

I have tested today for sure again on the same environment:

Latte Pro 1.0.11
PHPstorm 2023.1.1

and the bug is the same as in my original report. need to be fixed.

**Comment by mesour** [comment]
Duplicity for https://github.com/mesour-intellij-plugins/latte-pro-issues/issues/98
