### ISSUE TITLE
Version 1.1.0 causing issues with indexing of php files

### ISSUE THREAD

**Issue by Creeperface01** [mesour-intellij-plugins/latte-pro-issues#138]
**Describe the bug**
This usually results in infinite analyzing and phpstorm needs to be restarted

Not sure if the exception is related though
```
Cannot read scheme /Users/janbednar/PhpstormProjects/ipsos_elis_docker/application/elis/.idea/shelf/Uncommitted_changes_before_Checkout_at_09_08_2023_10_52__Changes_.xml
   
   org.jdom.JDOMException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
	at com.intellij.openapi.util.JDOMUtil.load(JDOMUtil.java:327)
	at com.intellij.configurationStore.schemeManager.SchemeLoader.loadScheme(schemeLoader.kt:192)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:261)
	at com.intellij.openapi.vcs.changes.shelf.ShelveChangesManager.projectOpened(ShelveChangesManager.java:224)
	at com.intellij.openapi.vcs.changes.shelf.ShelveChangesManager$PostStartupActivity.runActivity(ShelveChangesManager.java:1466)
	at com.mesour.intellij.latte.h.e.runActivity(SourceFile:12)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:327)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:72)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invoke(StartupManagerImpl.kt:264)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invoke(StartupManagerImpl.kt:263)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:199)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:263)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:72)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: com.fasterxml.aalto.WFCException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
	at com.fasterxml.aalto.stax.StreamReaderImpl.throwWfe(StreamReaderImpl.java:1777)
	at com.fasterxml.aalto.stax.StreamReaderImpl.throwUnexpectedEOI(StreamReaderImpl.java:1796)
	at com.fasterxml.aalto.stax.StreamReaderImpl.handlePrologEoi(StreamReaderImpl.java:1756)
	at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:810)
	at com.intellij.openapi.util.SafeStAXStreamBuilder.build(SafeStAXStreamBuilder.java:99)
	at com.intellij.openapi.util.JDOMUtil.load(JDOMUtil.java:320)
	... 20 more
```

**Environment (please complete the following information):**
 - PhpStorm version 2023.2.2
 - Plugin version 1.1.0

**To Reproduce**
Usually it's enough to close and reopen the project.

**Comment by Creeperface01** [comment]
Ah I haven't noticed the new patch. Seems to be fixed now. Thank you
