### ISSUE TITLE
intellij-latte-pro.xml throws an exception

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/latte-pro-issues#60]
**Environment:**
 - PhpStorm version [e.g. 2022.2]
 - Plugin version [1.0.7]

Exception happened when I wrote last change to file linked bellow (rename of filter urlUlid to urlUid)

https://github.com/orisai/cmf/blob/8524508759658e5fbecd88a104a1a50c171b374b/stubs/intellij-latte-pro.xml

Not sure what could be wrong, file is compatible with .dtd schema and the 'types' listed in exception is afaik also valid.

```txt
java.lang.InternalError: java.io.InvalidClassException: com.mesour.intellij.latte.configuration.settings.g; incompatible types for field a
	at java.base/java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:571)
	at java.base/java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:409)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1147)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.base/java.util.LinkedHashMap.internalWriteEntries(LinkedHashMap.java:334)
	at java.base/java.util.HashMap.writeObject(HashMap.java:1497)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1201)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1526)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1582)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1539)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at com.mesour.intellij.latte.configuration.c.a.a.a(SourceFile:11)
	at com.mesour.intellij.latte.configuration.c.a.a.save(SourceFile:6)
	at com.intellij.util.indexing.InputMapExternalizer.save(InputMapExternalizer.java:69)
	at com.intellij.util.indexing.InputMapExternalizer.save(InputMapExternalizer.java:19)
	at com.intellij.util.indexing.impl.forward.AbstractForwardIndexAccessor.serializeToByteSeq(AbstractForwardIndexAccessor.java:81)
	at com.intellij.util.indexing.impl.forward.AbstractForwardIndexAccessor.serializeValueToByteSeq(AbstractForwardIndexAccessor.java:69)
	at com.intellij.util.indexing.impl.forward.AbstractForwardIndexAccessor.serializeIndexedData(AbstractForwardIndexAccessor.java:50)
	at com.intellij.util.indexing.impl.forward.AbstractForwardIndexAccessor.serializeIndexedData(AbstractForwardIndexAccessor.java:44)
	at com.intellij.util.indexing.impl.MapReduceIndex.updateForwardIndex(MapReduceIndex.java:278)
	at com.intellij.util.indexing.impl.storage.TransientFileContentIndex.updateForwardIndex(TransientFileContentIndex.java:88)
	at com.intellij.util.indexing.impl.MapReduceIndex.lambda$prepareUpdate$4(MapReduceIndex.java:263)
	at com.intellij.util.indexing.impl.UpdateData.updateForwardIndex(UpdateData.java:63)
	at com.intellij.util.indexing.impl.MapReduceIndex.updateWithMap(MapReduceIndex.java:354)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.updateWithMap(MapReduceIndexBase.java:106)
	at com.intellij.util.indexing.impl.MapReduceIndex$IndexUpdateComputable.compute(MapReduceIndex.java:390)
	at com.intellij.util.indexing.impl.MapReduceIndex$IndexUpdateComputable.compute(MapReduceIndex.java:372)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.lambda$mapInputAndPrepareUpdate$3(CompositeInvertedIndexBase.java:73)
	at com.intellij.util.indexing.IndexInfrastructureExtensionUpdateComputation.compute(IndexInfrastructureExtensionUpdateComputation.java:27)
	at com.intellij.util.indexing.IndexInfrastructureExtensionUpdateComputation.compute(IndexInfrastructureExtensionUpdateComputation.java:11)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$runUpdateForPersistentData$27(FileBasedIndexImpl.java:1705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$runUpdateForPersistentData$28(FileBasedIndexImpl.java:1705)
	at com.intellij.util.indexing.StorageBufferingHandler.runUpdate(StorageBufferingHandler.java:22)
	at com.intellij.util.indexing.FileBasedIndexImpl.runUpdateForPersistentData(FileBasedIndexImpl.java:1704)
	at com.intellij.util.indexing.SingleIndexValueApplier.doApply(SingleIndexValueApplier.java:67)
	at com.intellij.util.indexing.SingleIndexValueApplier.apply(SingleIndexValueApplier.java:55)
	at com.intellij.util.indexing.FileIndexesValuesApplier.apply(FileIndexesValuesApplier.java:112)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1358)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1759)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1756)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1776)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:811)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:292)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:397)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:366)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:1139)
	at com.intellij.util.indexing.FileBasedIndexEx.processValues(FileBasedIndexEx.java:271)
	at com.intellij.util.indexing.FileBasedIndexEx.processValues(FileBasedIndexEx.java:259)
	at com.intellij.xml.index.IndexedRelevantResource.getResources(IndexedRelevantResource.java:50)
	at com.intellij.xml.index.XmlNamespaceIndex.getResourcesByNamespace(XmlNamespaceIndex.java:69)
	at com.intellij.xml.index.XmlNamespaceIndex.guessDtd(XmlNamespaceIndex.java:262)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.getNsDescriptorFormDocType(XmlDocumentImpl.java:296)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.getDefaultNSDescriptorInner(XmlDocumentImpl.java:230)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.lambda$getDefaultNSDescriptor$0(XmlDocumentImpl.java:147)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.getDefaultNSDescriptor(XmlDocumentImpl.java:158)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:229)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:99)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.URLReference.resolve(URLReference.java:104)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.hasBadResolve(XmlHighlightVisitor.java:530)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.doCheckRefs(XmlHighlightVisitor.java:453)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.checkReferences(XmlHighlightVisitor.java:445)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.visitXmlDoctype(XmlHighlightVisitor.java:535)
	at com.intellij.psi.impl.source.xml.XmlDoctypeImpl.accept(XmlDoctypeImpl.java:176)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.visit(XmlHighlightVisitor.java:596)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:347)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:285)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:606)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:276)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:221)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.io.InvalidClassException: com.mesour.intellij.latte.configuration.settings.g; incompatible types for field a
	at java.base/java.io.ObjectStreamClass.matchFields(ObjectStreamClass.java:2391)
	at java.base/java.io.ObjectStreamClass.getReflector(ObjectStreamClass.java:2286)
	at java.base/java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:568)
	... 119 more

```

**Comment by mesour** [comment]
@mabar please try it in `1.0.7`
